### ISSUE TITLE
Product ecommerce template is giving permissions issues

### ISSUE THREAD

**Issue by walkerblackwell** [OCA/product-pack#10]
The current code throws permissions issues for non-admin users or Public users when viewing a product that is a pack. There is a missing sudo(). somewhere in a template xml I think.

best regards,
-Walker

**Comment by rousseldenis** [comment]
@walkerblackwell This is not an issue. When installing website_sale, acl are modified to let all people read products. I think a module like website_product_pack or... should be done.

**Comment by pedrobaeza** [comment]
Yeah, that's it basically. Maybe it can be included in main module for not requiring that extra module, but what is clear is that "current product_pack_*" modules are not compatible with `website_sale`, as the original scope doesn't include it.
