### ISSUE TITLE
[14.0] sale_product_pack : Duplicating order with pack lines, new lines of components are added

### ISSUE THREAD

**Issue by Olimalt85** [OCA/product-pack#107]
**Module :  sale_product_pack**
Version : 14.0

When i duplicated my order with a product composed of other packs, some new lines with components are added

**Steps to reproduce the behavior:**
1. Create your packs of products
![image](https://user-images.githubusercontent.com/70909428/200564030-09e1816a-a6a2-425c-b65f-41152f98db88.png)
![image](https://user-images.githubusercontent.com/70909428/200564174-3f8ab567-d86d-4777-b019-43a0a75dabcf.png)
![image](https://user-images.githubusercontent.com/70909428/200564241-95c2b8d4-bc10-4a13-945d-77a1cc8da988.png)

2. Create a sale order with this pack product (pack 1)
(Pack column is the field 'pack_parent_line_id')
![image](https://user-images.githubusercontent.com/70909428/200564677-c5af645f-0995-4a76-930c-1f7c061375e3.png)

3. Duplicate the order : 
![image](https://user-images.githubusercontent.com/70909428/200565090-6b05123f-24eb-409c-b208-794449abb51d.png)

**Result :** 
![image](https://user-images.githubusercontent.com/70909428/200565186-6d0215e2-46ff-4248-a7c4-b8c018fb7669.png)

**Expected :** 
There should't be new lines added.

I first met the problem in my local odoo but then i tried in the runbot and it has the same behaviour.

**Comment by pedrobaeza** [comment]
The module is not prepared for nesting product packs. If you want, you can contribute with:

- Adding such comment on the ROADMAP of the module.
- Also adding a domain to prevent to select product packs on the pack lines.
- Or making this to work.

**Comment by Olimalt85** [comment]
Here is what i did to be able to duplicate them without creating new lines and keeping the link between the componants and pack_parent_line_id.

I suppose that we can do it better 

`
from odoo import api, models, fields


class SaleOrder(models.Model):
    _inherit = "sale.order"

    #I need this field in the sale order to avoid them create lines of composants in the expand_pack_line method when i duplicate one order
    is_copy = fields.Boolean("Is a copy")

    def _reset_sequence_before_copy(self):
        '''I need this method to deduplicate lines that have the same sequence in my order before i duplicate it (from module sale_order_line_sequence)'''
        for rec in self:
            current_sequence = 1
            for line in sorted(rec.order_line, key=lambda x: (x.sequence, x.id)):
                if line.sequence != current_sequence:
                    line.sequence = current_sequence
                current_sequence += 1

    def copy(self, default=None):

        #I deduplicate the sequences of the order lines because i will use it to identify and link the new lines to the original lines
        self._reset_sequence_before_copy()

        #I am using the field is_copy to avoid creating new line of pack when a pack is a copy from another pack
        if default:
            default['is_copy']=True
        else:
            default={'is_copy':True}
        sale_copy = super(SaleOrder, self).copy(default)

        #Delete the componants products because we are going to recopy them
        sale_copy.order_line.filtered(lambda l: l.pack_parent_line_id).unlink()


        #I copy the sequence number of the original line to keep the same sequence order
        for lines in sale_copy.order_line:
            lines.copied_sale_line_id = self.order_line.filtered(lambda r:r.sequence == lines.sequence and r.product_id.id == lines.product_id.id).id

        #search all the lines that have been deleted by the sale_product_pack module
        lines_to_copy_from_old = self.order_line.filtered(
                    lambda l: l.pack_parent_line_id
                )

        #Copy them into the new order with the link to the original line and with its sequence
        for line in lines_to_copy_from_old:
            line.copy(default={'order_id': sale_copy.id,
                               'copied_sale_line_id': line.id,
                               'sequence': line.sequence})

        #Select all the lines that are liked to componants lines in the the order
        new_pack_lines = sale_copy.order_line.filtered(lambda r: r.copied_sale_line_id.pack_child_line_ids)

        #Modify field pack_parent_line_id of the componants that have been duplicated
        for new_pack_line in new_pack_lines:
            lines_to_link_to_current_pack = sale_copy.order_line.filtered(lambda r: r.id in new_pack_line.copied_sale_line_id.pack_child_line_ids.ids)
            lines_to_link_to_current_pack.write({'pack_parent_line_id': new_pack_line.id})

        #Disable the field is_copy so that we can add the pack products and allow it to add the componants lines
        sale_copy.is_copy=False
        return sale_copy

class SaleOrderLine(models.Model):
    _inherit = "sale.order.line"

    def expand_pack_line(self, write=False):
        if not self.order_id.is_copy:
            super(SaleOrderLine, self).expand_pack_line(write)

    copied_sale_line_id = fields.Many2one(
        "sale.order.line",
        "Copied sale_line_id",
        help="The copied sale_line_id.",
    )

`
