### ISSUE TITLE
Need a module for pos

### ISSUE THREAD

**Issue by am-technix** [OCA/product-pack#108]
## Module stock-product-pack
The name of the module that has a bug.

## Describe the bug
Il we use a product of type PACK in a pos.order, the picking made by the pos order doesn't make stock moves for the product components.

## To Reproduce

1.Create a product pack with 2 products
2.Sell this product in pos.order and validate
3.Test the stock of the 2 products, it has not decrease

**Expected behavior**
Same as for the sale.orders when the stock.picking are created

**Comment by pedrobaeza** [comment]
There's no such module. You are free to implement it or to fund someone to do it. See also #64
