### ISSUE TITLE
"Pack Modifiable" for Pack component price option "Totalized in main product"

### ISSUE THREAD

**Issue by v-garcies** [OCA/product-pack#16]
A good improvement would be to allow the option "Pack Modifiable" with the option "Totalized in main product" selected :

![Capture d’écran 2020-04-17 à 14 14 25](https://user-images.githubusercontent.com/19540535/79568654-80b57400-80b6-11ea-9cea-d3943ac2d563.png)

In this way, it would be possible to calculate the real price of a package without specifying the details to the client.

**Comment by gregory-moka** [comment]
Hello, I'm interrested in this feature, but I'm thinking about the way to manage the packed product on sale order.

The actual behaviour is to prevent order line modification with an alert. If the product is "customize ready", we should see an unlock icon that shows we can replace the order line prouct with another one :  

![image](https://user-images.githubusercontent.com/45974412/102764199-0fcc0780-437b-11eb-97d2-0f951a451bf7.png)

In that case, 2 options :  
- We allow to replace this line with any product of the catalog
- We restrict this list to alternative products defined on the Pack product.

**Comment by chienandalu** [comment]
There's an ongoing PR similar to this requirement: https://github.com/OCA/product-pack/pull/26 You can help adding your functional review

**Comment by gregory-moka** [comment]
Hello, @v-garcies, this issue can be closed ?
