### ISSUE TITLE
[sale_product_pack] can't update quantity when sale is not draft

### ISSUE THREAD

**Issue by hparfr** [OCA/product-pack#20]
With module sale_product_pack

In a sale order with state = draft, when you change the ordered quantity of the parent product, the child product is updated.

But, when sale is confirmed, updating the ordered quantity of the parent product do not update the child product anymore.

@ernestotejeda 
What is the reason for this behavior ?
https://github.com/OCA/product-pack/blame/12.0/sale_product_pack/models/sale_order_line.py#L42

**Comment by pedrobaeza** [comment]
No specific reason except historic ones... Can you PR with this taking into account all possibilities.

**Comment by hparfr** [comment]
It's ok for you if I just just remove the state == 'draft' from the condition ?

**Comment by pedrobaeza** [comment]
Not sure if that's enough. It would be good to add tests for all that part that everything fits.
