### ISSUE TITLE
The package price is calculated twice in the online shop

### ISSUE THREAD

**Issue by baba75** [OCA/product-pack#35]
When Pack Type is 'detailed', Pack component is 'Detailed per component' and Pack Modifiable is set, when you add to cart on the shop the price is calculated twice.
![Schermata 2021-01-27 alle 12 57 08](https://user-images.githubusercontent.com/17760908/105988287-b359b780-609f-11eb-9cb7-622de23fcfd0.png)

**Comment by pedrobaeza** [comment]
Module is not compatible with e-commerce. There's the need of a `website_product_pack`.

Closing as no issue, but missing feature.
