### ISSUE TITLE
The FATHER product of the pack leaves it pending

### ISSUE THREAD

**Issue by juanframunoz** [OCA/product-pack#45]
When we sell a pack, all associated products are discounted from stock, but at the end of the delivery note, the FATHER product of the pack leaves it pending (along with other products that may be pending shipment).

These packs have to be marked as inventory, otherwise it does not show the stock of the packs.

**Comment by pedrobaeza** [comment]
Being discussed in https://github.com/OCA/product-pack/pull/40

**Comment by chienandalu** [comment]
This can be closed as the PR solving the issue was merged, isn't it?
