### ISSUE TITLE
Add product pack app

### ISSUE THREAD

**Issue by rousseldenis** [OCA/product-pack#59]
I would like your advice on this.

I want to make a 'product pack' app, but there are several approaches.

- Either we can define a product_pack_base that allows to define menus, maybe access rights, ... and base other modules on top of this
- Define product_pack module as 'application' and do stuff from above.
- Define a new module that aggregates the needed ones to build the app.

Thanks for your feedback

**Comment by pedrobaeza** [comment]
I see the second option the more suitable, but still it would be a bit weird to have a top-icon only for configuring packs (and they are at the end products). It would better that Odoo defines such "Products" top level icon (the same as "Contacts"). Or maybe we should add in OCA/product-attribute such `product_app` module, and adapt `product_pack` for having the corresponding features when added to a specific group?

**Comment by rousseldenis** [comment]
> I see the second option the more suitable, but still it would be a bit weird to have a top-icon only for configuring packs (and they are at the end products). It would better that Odoo defines such "Products" top level icon (the same as "Contacts"). Or maybe we should add in OCA/product-attribute such `product_app` module, and adapt `product_pack` for having the corresponding features when added to a specific group?

My aim (I will make a PR soon) is to add some features around. So, having those features gathered at the same place would be convenient.

I like your idea for managing products. But I cannot choose. Between both my heart goes back and forth :smiley:

**Comment by pedrobaeza** [comment]
OK, I can accept to promote `product_pack` as an application and give a new flaw specific group for handling that with top level icon, while keeping the same permissions and visibility in `sale_product_pack`.

**Comment by rousseldenis** [comment]
I can do PR(s) for that if you want

**Comment by pedrobaeza** [comment]
The next challenge is to find a good icon...

**Comment by rousseldenis** [comment]
> The next challenge is to find a good icon...

I remember Rafael did a tool for that no ?

**Comment by pedrobaeza** [comment]
It was @chienandalu at https://github.com/OCA/maintainer-tools/pull/491

I meant to find the proper icon that represents correctly the "pack" concept.

**Comment by chienandalu** [comment]
It's sort of abandoned. This tool is cool for it: https://spilymp.github.io/ibo/

**Comment by pedrobaeza** [comment]
But your tool works well, isn't it? And I like the possibility to have the original SVG for doing composed icons later for subsequent modules.

**Comment by chienandalu** [comment]
Yeah, it's generating a pdf for now, and the user has to convert it to svg. Also chrome headless is a bit mucho overhead for the feature...

**Comment by rousseldenis** [comment]
![image](https://user-images.githubusercontent.com/19529533/146222586-30f523c8-a7f2-43f9-ab3e-d279c21c9247.png)

**Comment by rousseldenis** [comment]
![image](https://user-images.githubusercontent.com/19529533/146223021-d6f751fc-7308-4d51-bb39-794c20e9bb3f.png)

**Comment by rousseldenis** [comment]
![image](https://user-images.githubusercontent.com/19529533/146223092-576d1cf3-8252-4b20-81e3-b53f6a8ed18e.png)

**Comment by rousseldenis** [comment]
I personnally like the second one

**Comment by pedrobaeza** [comment]
Well, I see that for layers (like GeoEngine, that I remember to have something similar), but right now I don't have a good alternative. Maybe a box with things inside, but that should be a custom one. If you like it, I can design it manually without relying on FontAwesome.

**Comment by pedrobaeza** [comment]
What do you think about this one?

![icon](https://user-images.githubusercontent.com/7165771/146254657-9a06b414-ad26-49a7-9f92-bd7543318745.png)

Compressed SVG
[icon.zip](https://github.com/OCA/product-pack/files/7722236/icon.zip)

**Comment by rousseldenis** [comment]
> What do you think about this one?
> 
> ![icon](https://user-images.githubusercontent.com/7165771/146254657-9a06b414-ad26-49a7-9f92-bd7543318745.png)
> 
> Compressed SVG [icon.zip](https://github.com/OCA/product-pack/files/7722236/icon.zip)

Ohh yes ! 

Didn't know you had graphic designer skills ! :+1:

**Comment by rousseldenis** [comment]
I'm doing the PR for that

**Comment by pedrobaeza** [comment]
Let's keep the PR opened, sorry.
