### ISSUE TITLE
i installed the 2 app but delivery stop at validate  

### ISSUE THREAD

**Issue by alielnagar** [OCA/product-pack#63]
i installed the 2 app but delivery stop at validate  in sales order 
odoo 14
please help or fix it

**Comment by pedrobaeza** [comment]
Please specify detailed steps to reproduce the problem and Odoo version.

**Comment by alielnagar** [comment]
after search i need the 3rd app 
sales product pack 
(delivery in sales order ) 
when you will migrate it ?
please hurry up
thank you
