### ISSUE TITLE
Pack product not reserved when storable

### ISSUE THREAD

**Issue by Meisolsson** [OCA/product-pack#68]
## Module
stock_product_pack

## Describe the bug
When creating a delivery the pack line is not reserving its items. This seems to have been discussed in #11 but never fixed.

## To Reproduce
14.0.1.0.1

1. Create a product pack as "Storable Product".
2. Add some products to the pack.
3. Make sure that the "Pack Display Type" is "Detailed".
4. Make sure that the "Pack Component Type" is "Ignored".
5. Make sure that the "Don't create move" is not checked.
6. Create a sale order with the pack and confirm it.
7. Open the delivery.

**Expected behavior**
The pack line should have its items reserved.

**Additional context**

**Comment by pedrobaeza** [comment]
Check #38 for not having to be storable.

**Comment by Meisolsson** [comment]
Alright, I see. Is there any reason for that not being merged?

Might consider porting that to v14 otherwise.

**Comment by pedrobaeza** [comment]
Test it and give your review for complying with OCA rules.

**Comment by Meisolsson** [comment]
Alright will look at it.

Another thing does cross my mind here. When I create a delivery with a pack when it is a consumable it will never be correctly backordered.

For instance if I have two products
* Product A is a "Storable Product"
* Product B is a "Consumable" Product **Pack** (using #38)

Product B has 5 of product A in its pack and we have 10 product A in stock.

We make a order for 3 product B (thus 15 product A) and confirm the order. Now we have a delivery ready, we validate that and allow it to create a backorder. This will create a backorder BUT the backorder will only contain 5 of product A. 

I would as a user have assumed that 1 of product B would have been backordered as well since it's technically not in stock anymore.

I know that one can handle that manually by changing the "Done" quantity but it still feels like the system should handle that.

**Comment by Meisolsson** [comment]
@pedrobaeza Any thoughts?

**Comment by pedrobaeza** [comment]
No, and you shouldn't mix things in the same thread, so I'm marking it as off-topic. Open a new issue.
